version: '3.8'
services:
  db:
    container_name: bd_socialpet
    image: mysql:latest
    environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_USER=socialpet
        - MYSQL_PASSWORD=root
        - MYSQL_DATABASE=socialpet
    ports:
      - 3306:3306
  socialpet:
    container_name: app_socialpet
    build: "./"
    ports:
      - "8080:8080"
    environment:
      JAVA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005"


